modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "vmtranslationupdate"
version = "${version}"
displayName = "VMTranslationUpdateMod"
displayURL = "https://github.com/VM-Chinese-translate-group/VM-Chinese-Group-Update"
authors = "Wulian233, TexTrue"
description = '''
VM汉化组用于检查汉化补丁更新的MOD
'''
#logoFile = ""

[[dependencies.vmtranslationupdate]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,]"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "architectury"
mandatory = true
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "cloth_config"
mandatory = true
versionRange = "[4,)"
ordering = "AFTER"
side = "BOTH"