modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "vmupdate"
version = "${version}"
displayName = "VMTranslationUpdateMod"
authors = "Wulian233, TexTrue"
description = '''
VM汉化组用于检查汉化补丁更新的MOD
'''
#logoFile = ""

[[dependencies.vmupdate]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmupdate]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmupdate]]
modId = "architectury"
mandatory = true
versionRange = "[4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vmupdate]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"