modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "vmtranslationupdate"
version = "${version}"
displayName = "VM Translation Update"
displayURL = "https://github.com/VM-Chinese-translate-group/VM-Chinese-Group-Update"
authors = "Wulian233, TexTrue, Litchiiiiiii"
description = '''
一个用于检查汉化补丁更新和自动下载资源包的模组。
'''
logoFile = "vmtranslationupdate.png"

[[dependencies.vmtranslationupdate]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.19.4]"
ordering = "NONE"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "architectury"
mandatory = true
versionRange = "[4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vmtranslationupdate]]
modId = "cloth_config"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"